### ISSUE TITLE
Generate file path is platform dependent

### ISSUE THREAD

**Issue by aleung** [icholy/gulp-tsconfig-files#8]
On windows, the files array populated contain platform specific delimiter `\`:

```
"files": [
  "src\\index.ts",
  "typings\\tsd.d.ts"
]
```

**Comment by icholy** [comment]
What behaviour do you expect?

**Comment by aleung** [comment]
I expect it to be:

```
"files": [
  "src/index.ts",
  "typings/tsd.d.ts"
]
```

It works fine on both Windows and Linux.

Then it will not cause unnecessary change into source control when switching development platform (team members may use different OS platforms).

**Comment by icholy** [comment]
Ah, ok I didn't know that. Ill fix that.

**Comment by icholy** [comment]
@aleung ok, you can set the `posix` flag to get your desired behaviour.

**Comment by aleung** [comment]
This issue isn't fixed.

`path.posix.normalize(filePath)` does **NOT** change separator from backslash to slash. It assumes the input path is already using posix separator. See source code: https://github.com/jden/node-path-posix/blob/master/index.js (which is a clone)

This issue might be fixed by string replace: 

```
filePath.replace(/\\/g, path.sep);
```

**Comment by aleung** [comment]
Below code test passed on my WIN platform:

```
if (options.posix && path.sep === '\\') {
  filePath = filePath.replace(/\\/g, path.posix.sep);
}
```

**Comment by icholy** [comment]
PR please :)

**Comment by gretro** [comment]
Was this pushed on NPM? Because I still have the same issue.

**Comment by icholy** [comment]
No, I forgot. I'll do it Tuesday

**Comment by aleung** [comment]
@icholy Just a ping. Have not published to NPM.

**Comment by icholy** [comment]
@aleung published
